/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import cordinator.Cordinator;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Filip
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * 
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabelDobrodosao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelKorisnickoIme = new javax.swing.JLabel();
        jButtonIzmenaLekar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUnosPacijenta = new javax.swing.JMenuItem();
        jMenuItemPrikazPacijenata = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUnosUsluge = new javax.swing.JMenuItem();
        jMenuItemPrikazUsluga = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemUnosStrucneSpreme = new javax.swing.JMenuItem();
        jMenuItemPrikazStrucnihSprema = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemUnosRacuna = new javax.swing.JMenuItem();
        jMenuItemPrikazRacuna = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem za poslovanje klinike");

        jLabelDobrodosao.setText("Dobrodosli, ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trenutno prijavljeni lekar"));

        jLabel1.setText("Ime :");

        jLabel3.setText("Mail:");

        jLabel4.setText("Korisnicko ime:");

        jLabelIme.setText("jLabel2");

        jLabelMail.setText("jLabel2");

        jLabelKorisnickoIme.setText("jLabel2");

        jButtonIzmenaLekar.setText("Izmena ličnih podataka");
        jButtonIzmenaLekar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmenaLekarActionPerformed(evt);
            }
        });

        jLabel2.setText("Prezime:");

        jLabelPrezime.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPrezime)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jButtonIzmenaLekar)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKorisnickoIme)
                            .addComponent(jLabelIme))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIme))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPrezime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMail)
                    .addComponent(jButtonIzmenaLekar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelKorisnickoIme))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenu1.setText("Pacijent");

        jMenuItemUnosPacijenta.setText("Unos pacijenta");
        jMenuItemUnosPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosPacijentaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosPacijenta);

        jMenuItemPrikazPacijenata.setText("Prikaz svih pacijenata");
        jMenuItemPrikazPacijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazPacijenataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPrikazPacijenata);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usluga");

        jMenuItemUnosUsluge.setText("Unos usluge");
        jMenuItemUnosUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosUslugeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnosUsluge);

        jMenuItemPrikazUsluga.setText("Prikaz svih usluga");
        jMenuItemPrikazUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazUslugaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPrikazUsluga);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Strucna sprema");

        jMenuItemUnosStrucneSpreme.setText("Unos strucne spreme");
        jMenuItemUnosStrucneSpreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosStrucneSpremeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemUnosStrucneSpreme);

        jMenuItemPrikazStrucnihSprema.setText("Prikaz svih strucnih sprema");
        jMenuItemPrikazStrucnihSprema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazStrucnihSpremaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPrikazStrucnihSprema);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Račun");

        jMenuItemUnosRacuna.setText("Unos novog racuna");
        jMenuItemUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemUnosRacuna);

        jMenuItemPrikazRacuna.setText("Prikaz svih racuna");
        jMenuItemPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPrikazRacuna);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDobrodosao)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelDobrodosao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosPacijentaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajPacijentaFormu();
    }//GEN-LAST:event_jMenuItemUnosPacijentaActionPerformed

    private void jMenuItemUnosUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosUslugeActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajUsluguFormu();
    }//GEN-LAST:event_jMenuItemUnosUslugeActionPerformed

    private void jMenuItemPrikazUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazUslugaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazUslugeFormu();
    }//GEN-LAST:event_jMenuItemPrikazUslugaActionPerformed

    private void jMenuItemUnosStrucneSpremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosStrucneSpremeActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajStrucnuSpremuFormu();
    }//GEN-LAST:event_jMenuItemUnosStrucneSpremeActionPerformed

    private void jMenuItemPrikazPacijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazPacijenataActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazPacijenataFormu();
    }//GEN-LAST:event_jMenuItemPrikazPacijenataActionPerformed

    private void jMenuItemUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosRacunaActionPerformed
        try {
            // TODO add your handling code here:
            Cordinator.getInstance().otvoriDodajracunFormu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUnosRacunaActionPerformed

    private void jMenuItemPrikazStrucnihSpremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazStrucnihSpremaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikaziStrucnaSpremaFormu();
    }//GEN-LAST:event_jMenuItemPrikazStrucnihSpremaActionPerformed

    private void jMenuItemPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRacunaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazRacunaFormu();
    }//GEN-LAST:event_jMenuItemPrikazRacunaActionPerformed

    private void jButtonIzmenaLekarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmenaLekarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzmenaLekarActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmenaLekar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDobrodosao;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelKorisnickoIme;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemPrikazPacijenata;
    private javax.swing.JMenuItem jMenuItemPrikazRacuna;
    private javax.swing.JMenuItem jMenuItemPrikazStrucnihSprema;
    private javax.swing.JMenuItem jMenuItemPrikazUsluga;
    private javax.swing.JMenuItem jMenuItemUnosPacijenta;
    private javax.swing.JMenuItem jMenuItemUnosRacuna;
    private javax.swing.JMenuItem jMenuItemUnosStrucneSpreme;
    private javax.swing.JMenuItem jMenuItemUnosUsluge;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelDobrodosao() {
        return jLabelDobrodosao;
    }

    public void setjLabelDobrodosao(JLabel jLabelDobrodosao) {
        this.jLabelDobrodosao = jLabelDobrodosao;
    }

    

    public JLabel getjLabelMail() {
        return jLabelMail;
    }

    public JLabel getjLabelIme() {
        return jLabelIme;
    }
    
    public JLabel getjLabelPrezime() {
        return jLabelPrezime;
    }

    public JLabel getjLabelKorisnickoIme() {
        return jLabelKorisnickoIme;
    }

    public JButton getjButtonIzmenaLekar() {
        return jButtonIzmenaLekar;
    }

    public void addBtnIzmeniProfilActionListener(ActionListener actionListener) {
        jButtonIzmenaLekar.addActionListener(actionListener);
    }
    
    
}
